# DAY 04 – Исключения, работа с сетью
## Классы, наследование, атрибуты классов и объектов
В рамках этого дня вы изучите исключения и работу с сетью в Python.

### Преамбула

Важная часть любого языка программирования высокого уровня - это исключения и способы обработки ошибок. Ошибки могут возникнуть всегда, и при этом не всегда по вине программиста. Например, при подключении к базе данных отключилась сеть или произошла ошибка записи в базу по каким-то ее внутренним причинам. Наше приложение должно уметь обрабатывать такие ситуации, поэтому мы должны научиться использовать исключения в нашем коде. Вторая тема, рассмотренная в этом уроке, это работа с сетью со стороны клиента. В рамках курса по разработке веб-приложений на питоне мы вообще-то будем писать бэкенд, т.е. логику, которая исполняется на сервере. Но также нам полезно понимать и то, как процесс передачи-получения данных устроен и с другой стороны - со стороны клиента.

### Цели

Наша цель - освоить работу с исключениями и сетью в питоне.

### Задание

В этом дне вас ждут 2 задачи, в одной из которых нужно будет описать вызовы и обработку исключений, а в другой - составить несколько запросов к удаленному серверу и отправить ответ на другой удаленный сервер. Как и в предыдущих днях, эти задачи можно проверить автоматически в Яндекс.Контесте по ссылке https://contest.yandex.ru/contest/40435/enter/

Что нужно сделать:
1. Напишите скрипт, решающий задачу, описанную по адресу https://contest.yandex.ru/contest/40435/problems/16/.
2. Напишите скрипт, решающий задачу, описанную по адресу https://contest.yandex.ru/contest/40435/problems/17/.

Все решения должны проходить соответствующие тесты из Яндекс.Контеста. Соответствие задач из контеста задачам из задания приведено в блокнотах с конспектами.

### Сдача работы и проверка

Вам нужно загрузить в GIT в папку `src` свой Jupyter Notebook, в котором заполнены ячейки, предусмотренные для решения заданий.
